### PR TITLE
125 only one metric shown in list if one is selected

### LINKED ISSUE #125: Only one metric shown in list, if one is selected
**Describe the bug**
When selecting metrics sometimes only one is shown, most likely connected with @ELEMENTLHERO sorting function

**To Reproduce**
Upload files, don't press the all metrics button, only choose one

**Expected behavior**
Only one is shown

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by ELEMENTLHERO**

### CODE REVIEW

File: src/components/Menu.tsx [hunk 1]
```diff
@@ -181,6 +181,22 @@ export default function Menu(props: MenuProps) {
     const newMap = new Map<string, Site>(siteProps);
     const PHI = (1 + Math.sqrt(5)) / 2;
     let index = newMap.size;
+    // sort metrics after name
+    setMetrics([...metrics].sort((a, b) => a.localeCompare(b)));
+    // sort sites after name
+    setSites(
+      sites.sort((a, b) => {
```
Comment (AntonOstman) [inline src/components/Menu.tsx:188]: would be nice with more descriptive variable names than a and b

**Review by AntonOstman — APPROVED** [review]
Looks good small and nice changes! I had one comment you can look at if you want to. Otherwise dont mind it!

**Review by AntonOstman — APPROVED** [review]
nice change!

**Review by ViktorAndersson99 — APPROVED** [review]
